name: INIT

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  rsync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: rsync para dk01
        uses: up9cloud/action-rsync@v1.4
        env:
          HOST: file.cett.dev.br
          USER: deploy
          KEY: ${{secrets.DEPLOY_SSH_KEY}}
          TARGET: /data/volume/dev/actions_teste
